/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: ec83d8b8c5b6b2c244418211316350e5)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	ASSETS: Fetcher;
	NODE_ENV: string;
	DB_DRIVER: string;
	DB_CONNECTION_LIMIT: string;
	LOG_LEVEL: string;
	JWT_ACCESS_SECRET: string;
	JWT_REFRESH_SECRET: string;
	AI_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/worker").GameOpsAiWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "DB_DRIVER" | "DB_CONNECTION_LIMIT" | "LOG_LEVEL" | "JWT_ACCESS_SECRET" | "JWT_REFRESH_SECRET">> {}
}
