/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 0e5e20ada2d86a06c913d8af8aa8917f)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	API_ORIGIN: string;
	JWT_ACCESS_SECRET: string;
	JWT_REFRESH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "API_ORIGIN" | "JWT_ACCESS_SECRET" | "JWT_REFRESH_SECRET">> {}
}
